---
title: "btg2_siRNA"
author: "Neelanjan Mukherjee"
date: "12/24/2020"
output: html_document
---


# Screen for regulators of Aldosterone


```{r setup, include=TRUE, echo=TRUE }

library(drc) # modeling tools
library(tidyverse) # your go to set of functions for messing w/data
library(RColorBrewer) # to make color schemes
#library(ggpubr) # publication quality ggplots ha ha ha
library(ggthemes) # additional themes for ggplot-ing
library(gridExtra) # allows arranging of plots (rows/columns...)
library(splitstackshape)
library(ggpubr)
library(here)

```

```{r files, include=TRUE, echo=TRUE}
# OD file
OD <- read_csv(here("data","screen","elisa","20210120_BTG3_ELISAall.csv"))
colnames(OD) <- c("Sample","Well","OD_450","OD_540","OD_570")


pb <- read_csv(here("data","screen","presto","20210120_BTG3_PBall.csv"))
colnames(pb) <- c("Sample","Well","viability_24","viability_48")


# join presto blue measurements with ELISA measurements
OD <- left_join(OD, pb[,-1], by = "Well")

OD$Sample <- ifelse(grepl("85|86", OD$Sample), yes = paste("BTG2",OD$Sample,sep = "_"), no = OD$Sample)


OD$Sample <- ifelse(grepl("water1|water2", OD$Sample), yes = paste("water",OD$Sample,sep = "_"), no = OD$Sample)



```

## ELISA model fit
Fit a 4-parameter model from the standard curve in order to identify the correct paramaters of a formula to convert fluorescence to aldosterone concentrations.

```{r model fit, include=TRUE, echo=FALSE}
# Subtract background signal (measured at 540nm) from target signal (measured at 450nm)
OD$corrected <- OD$OD_450 - OD$OD_540

standards <- OD %>% filter(grepl("std", Sample)) # one way of creating a new tibble that only contains your standards

nsb <- OD %>% filter(grepl("nsb", Sample)) # one way of creating a new tibble that only contains your NSBs

# create a tibble for the actual concentrations by std name
stdcrvdata <- data.frame(
  Sample=paste0("std",rep(seq(1,7,1),each=2)),
  known=rep(c(4000,1000,250,62.25,15.625,3.906,0),each=2)
  )

# sort standards by name to match the order of 'stdcrvdata' data.
standards <- standards %>% arrange(Sample) %>% select(c(Sample,corrected))

# sort stdcrvdata by name to match the order of 'standards' data.
stdcrvdata <- stdcrvdata %>% arrange(Sample)

# check if they are in the same order (I could change this to well location?)
stopifnot(identical(as.character(standards$Sample), as.character(stdcrvdata$Sample)))

# combine them together
stdcrvdata <- data.frame(standards,expected=stdcrvdata$known)

colnames(stdcrvdata)[2] <- "measured"


# take out zeros
stdcrvdata <- stdcrvdata %>% filter(expected > 0)

stdcrvdata$logconc <-log10(stdcrvdata$expected)# log10 from conc


# model the standard curve using generated points.  plot those points in red.
fit <- drm(formula =   measured ~ logconc , data = stdcrvdata, fct = LL.4())
summary(fit)

# This is a description of the variables and terms defined in the 'fit' model.
# x = the independent variable (Absorbance) (Concentration, estimated from the Absorbance)
# y = the dependent variable 
# The 4 estimated parameters consist of the following:

# the minimum value that can be obtained. (this is the ABS at conc. 0)
# a = fit$coefficients[2] 

# d = the maximum value that can be obtained (i.e. what happens at infinite dose)

# c = the point of inflection (i.e. the point on the S shaped curve halfway between a and d)

# b = Hill’s slope of the curve (i.e. this is related to the steepness of the curve at point c).

# Generate points from  model. Pick range from logconc
x <- seq(from = 0, to = 4, length=100)

# from OD ~ d + (a - d)/(1 + (logconc/cc)^b)
y <- (fit$coefficients[2]+ (fit$coefficients[3]- fit$coefficients[2])/(1+(x/fit$coefficients[4])^ fit$coefficients[1])) 


```

## Apply model to calculate aldosterone levels

```{r apply model, echo=FALSE}
# remove standards and NSB wells leaving only experimental measurements
OD <- OD %>% filter(!grepl("std|nsb", Sample))

# here we are applying the equation described above to...
OD$loganswer<- fit$coefficients[4]*(
  (
    (-1* fit$coefficients[3]+ OD$corrected)/
      (fit$coefficients[2]-OD$corrected))^(1/ fit$coefficients[1])
  )

OD$conc <- 10^OD$loganswer

# write.table(OD,file="20181012_aldosterone_ELISA_batch1_results.csv",sep=";")

OD$below <- OD$conc < min(stdcrvdata$expected)
OD$above <- OD$conc > max(stdcrvdata$expected)

plot(x = stdcrvdata$logconc, y = stdcrvdata$measured, main="log standard curve",
  xlim = c(min(x),max(x)),
  ylim = c(min(y),max(y))
     )
lines(x,y, lty="dotted", col="red")
lines(OD$loganswer, OD$corrected, type="points", col="blue")



  
```

## Analyze differences in aldosterone concentration and cell viability


```{r aldosterone calculations, echo=FALSE}

OD$Sample <- gsub(pattern = "mediaOnly", replacement = "media_NA_NA", x = OD$Sample)


OD <- separate(data = OD, col = Sample, into = c("target","siRNA","stim"), sep = "_")

OD$stim <- relevel(factor(OD$stim), ref = "unstim")


OD$siRNA <- relevel(factor(OD$siRNA), ref = "water")


bg <- OD %>% filter(target=="media") %>% summarise(mean(na.omit(conc))) %>% pull()

OD$conc <- OD$conc - bg

OD <- OD %>% filter(target!="media")


# add batch id to data
OD$batch <- rep("BTG2", nrow(OD) )


ggplot2::ggplot(data = OD, aes(y=conc, x = stim)) +
  geom_boxplot() +
  facet_wrap(~siRNA) +
  theme_minimal()

ggplot2::ggplot(data = OD, aes(x=stim, y=conc, color=stim)) +
  geom_boxplot() +
  geom_jitter(width = .25) +
  facet_grid(~siRNA) + 
  theme_few()
library(ggplot2)



ggplot2::ggplot(data = OD, aes(x=stim, y=conc/viability_24, color=stim)) +
  geom_boxplot() +
  geom_jitter(width = .25) +
  facet_grid(~siRNA) + 
  theme_few()



unstimData <- OD %>% filter(stim=="unstim")
unstimData_all.lm <- lm(conc ~ viability_24, data=unstimData) 
unstimData$residuals <- resid(unstimData_all.lm)
stimData <- OD %>% filter(stim=="stim")
stimData_all.lm <- lm(conc ~ viability_24, data=stimData) 
stimData$residuals <- resid(stimData_all.lm)

new_OD <- bind_rows(unstimData, stimData)

p_conc_PB_stim <- ggplot(data = OD %>% filter(stim=="stim"), aes(x=viability_24, y=conc)) +
  geom_point() +
  geom_smooth(method=lm, se=FALSE) +
  ggtitle("Stimulated: presto vs aldo") +
  ylab("aldo") +
  theme_few()


p_conc_PB_unstim <- ggplot(data = OD %>% filter(stim=="unstim"), aes(x=viability_24, y=conc)) +
  geom_point() +
  geom_smooth(method=lm, se=FALSE) +
  ggtitle("Unstimulated: presto vs aldo") +
  ylab("aldo") +
  theme_few()

p_aldonorm_stim <- ggplot2::ggplot(data = new_OD %>% filter(stim=="stim"), aes(x=siRNA, y=residuals)) +
  geom_boxplot() +
  geom_jitter(width = .25) +
  ggtitle("Stimulated: presto vs aldo") +
  ylab("aldo: PB residuals") +
  theme_few()

p_aldonorm_unstim <- ggplot2::ggplot(data = new_OD %>% filter(stim=="unstim"), aes(x=siRNA, y=residuals)) +
  geom_boxplot() +
  geom_jitter(width = .25) +
  ggtitle("Unstimulated: presto vs aldo") +
  ylab("aldo: PB residuals") +
  theme_few()


cowplot::plot_grid(
  p_conc_PB_unstim,
  p_conc_PB_stim,
  p_aldonorm_unstim,
  p_aldonorm_stim
)



write_csv(path = here("data","screen","processed","BTG2_kd_3.csv"), x = OD %>% arrange(target,siRNA,stim))
```


