---
title: "exvivo_H295R"
author: "Neelanjan Mukherjee"
date: "9/17/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(clusterProfiler)
library(enrichplot)
library(here)
library(tidyverse)
library(viridis)
library(pheatmap)
library(GeneOverlap)
library(fgsea)

`%notin%` <- Negate(`%in%`)
```



```{r gsea H295R ang}


# import angII DEG results
ang <- read_csv(here("data", "RNAseq", "edger_AngIIvsbasal.csv.gz")) %>% janitor::clean_names() 
# remove duplicated gene symbols
dups <- ang %>%  pull(symbol)
dups <- dups[duplicated(dups)==T]

ang <- ang %>% filter(symbol %notin% dups & log_cpm > 1) 



# identify significantly enriched gene sets for each time point

# using clusters from H295R
load(here("data","RNAseq", "clustGenes.R"))

myClustGenes <- myClust_annotated %>% 
  dplyr::select(cluster, symbol)



# define columns of Ang that contain fold-change values that  will be used for gsea
myLists <- select(ang,contains("log_fc")) %>% names
myLists <- myLists[c(1,4)]

# empty tibble that will store all enriched gene sets
my_enrichments <- tribble()

for (i in 1:length(myLists))  {
  geneList <- ang %>% pull(myLists[i])
  names(geneList) <- ang$symbol
  geneList <- sort(geneList, decreasing = TRUE)

  
  edo2 <- GSEA(geneList = geneList, pAdjustMethod = "fdr", 
               pvalueCutoff = 1,
               minGSSize = 2,
               maxGSSize = 4000,
               TERM2GENE = myClustGenes)
  tmp <- edo2@result
  
  tmp$genelist <- rep(myLists[i],nrow(tmp))
  my_enrichments <- bind_rows(my_enrichments, tmp)
  
  }

gsea_H295RvsExvivo_ang <- my_enrichments
gsea_H295RvsExvivo_ang$ID <- factor(gsea_H295RvsExvivo_ang$ID)
gsea_H295RvsExvivo_ang$genelist <- factor(gsea_H295RvsExvivo_ang$genelist)

gsea_H295RvsExvivo_ang$genelist <- relevel(gsea_H295RvsExvivo_ang$genelist, "log_fc_avsb_3")

p_ang_summary <- ggpubr::ggbarplot(gsea_H295RvsExvivo_ang, "ID", "NES",
  fill = "genelist", color = "genelist", palette = "Paired",
  label = F,
  position = position_dodge(0.9))


# gsea_H295RvsExvivo_ang <- my_enrichments %>% 
#   select(ID,NES,genelist) %>%
#   pivot_wider(names_from = ID, values_from = NES)
#   
# myDF <- data.frame(gsea_H295RvsExvivo_ang)[,-1]
# 
# rownames(myDF) <- gsub(pattern = "log_fc_avsb_", replacement = "", x = gsea_H295RvsExvivo_ang$genelist)
# 
# myDF <- myDF[order(colnames(myDF))]
# myDF <- t(myDF)
# 
# tmp <- my_enrichments %>% 
#   select(ID,pvalue,genelist) %>%
#   pivot_wider(names_from = ID, values_from = pvalue)
# 
# tmp <- data.frame(tmp)[,-1]
# 
# rownames(tmp) <- gsub(pattern = "log_fc_avsb_", replacement = "", x = gsea_H295RvsExvivo_ang$genelist)
# 
# tmp <- tmp[order(colnames(tmp))]
# tmp <- t(tmp)
# 
# 
# colnames(myDF) <- c("NES_3","NES_24")
# colnames(tmp) <- c("fdr_3","fdr_24")
# 
# enrichments <- cbind.data.frame(myDF,tmp) %>%  reshape2::melt()


# pheatmap::pheatmap(mat = myDF, cluster_rows = F, cluster_cols = F, color = viridis(20, option = "E", direction = 1, begin = 0, end = 1), border_color = "black", angle_col = 0, na_col = "black", number_color = "black", display_numbers = T, treeheight_row = 15, treeheight_col = 15, fontsize = 10, width = 4, height = 3, filename = here("fig3_exvivo-H295R","plots","H295R_Angexvivo_reduced.pdf"), silent = T)


```




```{r gsea H295R acth}


# import angII DEG results
acth <- read_csv(here("data", "RNAseq", "edger_ACTHvsbasal.csv.gz")) %>% janitor::clean_names() 
# remove duplicated gene symbols
dups <- acth %>%  pull(symbol)
dups <- dups[duplicated(dups)==T]

acth <- acth %>% filter(symbol %notin% dups & log_cpm > 1) 



# identify significantly enriched gene sets for each time point

# using clusters from H295R
load(here("data","RNAseq", "clustGenes.R"))

myClustGenes <- myClust_annotated %>% 
  dplyr::select(cluster, symbol)

# define columns of Ang that contain fold-change values that  will be used for gsea
myLists <- select(acth,contains("log_fc")) %>% names
myLists <- myLists[c(1,4)]
# empty tibble that will store all enriched gene sets
my_enrichments <- tribble()

for (i in 1:length(myLists))  {
  geneList <- acth %>% pull(myLists[i])
  names(geneList) <- acth$symbol
  geneList <- sort(geneList, decreasing = TRUE)

  
  edo2 <- GSEA(geneList = geneList, pAdjustMethod = "fdr", 
               pvalueCutoff = 1,
               minGSSize = 4,
               maxGSSize = 4000,
               TERM2GENE = myClustGenes)
  tmp <- edo2@result
  
  tmp$genelist <- rep(myLists[i],nrow(tmp))
  my_enrichments <- bind_rows(my_enrichments, tmp)
  
  }

gsea_H295RvsExvivo_acth <- my_enrichments
gsea_H295RvsExvivo_acth$ID <- factor(gsea_H295RvsExvivo_acth$ID)
gsea_H295RvsExvivo_acth$genelist <- factor(gsea_H295RvsExvivo_acth$genelist)

gsea_H295RvsExvivo_acth$genelist <- relevel(gsea_H295RvsExvivo_acth$genelist, "log_fc_avsb_3")

p_acth_summary <- ggpubr::ggbarplot(gsea_H295RvsExvivo_acth, "ID", "NES",
  fill = "genelist", color = "genelist", palette = "Paired",
  label = F,
  position = position_dodge(0.9))

p_NES_summary <- cowplot::plot_grid(p_acth_summary, p_ang_summary, nrow = 2)

ggsave(plot = p_NES_summary, filename = here("fig3_exvivo-H295R","plots","NES_summary.pdf"), device = "pdf", units = "in", width = 6, height = 4)
# gsea_H295RvsExvivo_acth <- my_enrichments %>% 
#   select(ID,NES,genelist) %>%
#   pivot_wider(names_from = ID, values_from = NES)
#   
# myDF <- data.frame(gsea_H295RvsExvivo_acth)[,-1]
# rownames(myDF) <- gsub(pattern = "log_fc_avsb_", replacement = "", x = gsea_H295RvsExvivo_acth$genelist)
# 
# myDF <- myDF[order(colnames(myDF))]
# myDF <- t(myDF)
# 
# tmp <- my_enrichments %>% 
#   select(ID,pvalue,genelist) %>%
#   pivot_wider(names_from = ID, values_from = pvalue)
# 
# tmp <- data.frame(tmp)[,-1]
# 
# rownames(tmp) <- gsub(pattern = "log_fc_avsb_", replacement = "", x = gsea_H295RvsExvivo_acth$genelist)
# 
# tmp <- tmp[order(colnames(tmp))]
# tmp <- t(tmp)
# 
# 
# myDF[tmp > .05 ] <- NA
# 

#pheatmap::pheatmap(mat = myDF, cluster_rows = F, cluster_cols = F, color = viridis(40, option = "E", direction = 1, begin = 0, end = 1), border_color = "black", angle_col = 0, na_col = "black", number_color = "black", display_numbers = T, treeheight_row = 15, treeheight_col = 15, fontsize = 10, width = 4, height = 3, filename = here("fig3_exvivo-H295R","plots","H295R_ACTHexvivo.pdf"), silent = T, gaps_row = c(4,9))
```


```{r ang plots}
myClust <-  split(myClust_annotated$symbol, myClust_annotated$cluster)

geneList <- ang %>% pull(log_fc_avsb_3)
names(geneList) <- ang$symbol
geneList <- sort(geneList, decreasing = TRUE)


  
fgseaRes <- fgsea(pathways = myClust, 
                  stats    = geneList,
                  minSize  = 5,
                  maxSize  = 5000)

p_as2_Ang_3 <- plotEnrichment(myClust[["as2"]], geneList)

geneList <- ang %>% pull(log_fc_avsb_24)
names(geneList) <- ang$symbol
geneList <- sort(geneList, decreasing = TRUE)

fgseaRes <- fgsea(pathways = myClust, 
                  stats    = geneList,
                  minSize  = 5,
                  maxSize  = 5000)

p_as4_Ang_24 <- plotEnrichment(myClust[["as4"]], geneList)




```


```{r acth plots}
myClust <-  split(myClust_annotated$symbol, myClust_annotated$cluster)

geneList <- acth %>% pull(log_fc_avsb_3)
names(geneList) <- acth$symbol
geneList <- sort(geneList, decreasing = TRUE)


  
fgseaRes <- fgsea(pathways = myClust, 
                  stats    = geneList,
                  minSize  = 5,
                  maxSize  = 5000)

p_as2_ACTH_3 <- plotEnrichment(myClust[["as2"]], geneList)

geneList <- acth %>% pull(log_fc_avsb_24)
names(geneList) <- acth$symbol
geneList <- sort(geneList, decreasing = TRUE)

fgseaRes <- fgsea(pathways = myClust, 
                  stats    = geneList,
                  minSize  = 5,
                  maxSize  = 5000)

p_as4_ACTH_24 <- plotEnrichment(myClust[["as4"]], geneList)




```

```{r}

p_runplots <- cowplot::plot_grid(p_as2_ACTH_3, p_as4_ACTH_24, p_as2_Ang_3,p_as4_Ang_24)

ggsave(plot = p_runplots, filename = here("fig3_exvivo-H295R","plots","runplots.pdf"), device = "pdf", units = "in", width = 6, height = 4)
```

